### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by D-Nice** [D-Nice/nbaser#1]
- [x] make unicode compatible version
- [x] read raw binary data for the encoder fuzz entrypoint
(already does this fine, reading all binary data passed...)
- [ ] test performance increase if doing binary search on base lookup table
- [x] https://github.com/D-Nice/nbaser/pull/4/commits/e189a07c1ada5595618a115d22a3b86022ca3845 consider predefinining baseAlphabet.toRunes
outside of the loop (presuming backend or compiler already optimize this) 
- [ ] implement code coverage once a non-obtrusive one becomes available for Nim
- [x] put this in a TODO.md or make a TODO issue...
- [ ] add more coverage for different GCs, or at least refc vs arc
- [ ] consider scheduled or even better, triggered action based on new Nim releases, to test compatibiltiy
- [ ] fix `realatively` typo in README
